@echo off
cd /d "%~dp0"
echo [1/4] creating venv from system python (with tkinter) ...
"C:\Users\92112\AppData\Local\Python\bin\python.exe" -m venv "%~dp0.venv"
echo [2/4] installing faster-whisper / deep-translator ...
"%~dp0.venv\Scripts\python.exe" -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple faster-whisper deep-translator
echo [3/5] installing SoundCard (pypi.org) ...
"%~dp0.venv\Scripts\python.exe" -m pip install SoundCard
echo [4/5] installing CUDA runtime libs for GPU (nvidia-cublas / cudnn) ...
"%~dp0.venv\Scripts\python.exe" -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple nvidia-cublas-cu12 nvidia-cudnn-cu12
echo [5/5] downloading whisper models (hf-mirror.com) ...
"%~dp0.venv\Scripts\python.exe" -X utf8 "%~dp0realtime_subtitle\download_model.py"
echo.
echo Install done. Run run.bat
pause
