@echo off
cd /d "%~dp0"
echo [1/4] creating venv from system python (with tkinter) ...
"C:\Users\92112\AppData\Local\Python\bin\python.exe" -m venv "%~dp0.venv"
echo [2/4] installing runtime deps (sherpa-onnx / onnxruntime / deep-translator) ...
"%~dp0.venv\Scripts\python.exe" -m pip install -i https://pypi.tuna.tsinghua.edu.cn/simple sherpa-onnx onnxruntime deep-translator requests numpy
echo [3/4] installing SoundCard (pypi.org) ...
"%~dp0.venv\Scripts\python.exe" -m pip install SoundCard
echo [4/4] downloading streaming ASR model (~240MB, hf-mirror.com) ...
"%~dp0.venv\Scripts\python.exe" -X utf8 -c "import sys; sys.path.insert(0, r'%~dp0realtime_subtitle'); import asr_stream; print(asr_stream.download_model() or 'MODEL DOWNLOAD FAILED')"
echo.
echo Install done. Run run.bat
pause
